### ISSUE TITLE
Github pages not active

### ISSUE THREAD

**Issue by Kevin-Oudai** [Yuvashrie/SIMPLE_INTEREST_CALCULATOR#1]
Hay you did not activate the github pages for the project. I will continue the review another day so you can get a chance to activate it. Also as i review it and i see any issues with it I will create it here so you can fix it.

**Comment by Kevin-Oudai** [comment]
you can close this issue. also i am  no longer responsible for grading your submission. you need to fix the colors of your app and change the range of the slider. that is all i can remember. good luck.

**Comment by Yuvashrie** [comment]
Ok. Thank you
